### ISSUE TITLE
Add license notice

### ISSUE THREAD

**Issue by nurupo** [roxlu/video_capture#2]
Under which license is your code distributed? I couldn't find any license notice in the repository.

Without a license we have no legal right to redistribute the code or produce derived works from it. It's like "look but don't touch" license.

**Comment by roxlu** [comment]
Hi nurupo, I've to dive into what kind of license I want to use; I guess it will be something like "You can use it however you use it + I'm not resonsible for any damage or how this library is used".  Any ideas? Btw, I see you're working on Tox; are you looking for a video capture library for Tox (which would be awesome) ?

**Comment by nurupo** [comment]
> I've to dive into what kind of license I want to use

I'd recommend using https://tldrlegal.com/ as a helper in choosing a license, people working on it provide a nice summery of what licenses are about, removing the burden of reading the long license statements. After you settle on something, read the entire license statement, just in case the provided summery is incorrect.
MIT, BSD and Apache are ones of the most common licenses. There are more of them though. I'd suggest to pick some common license people are used to, it generally makes things a lot easier for whoever whats to use your code.
This is not a legal advise.

> I see you're working on Tox; are you looking for a video capture library for Tox

We have [a Google Summer of Code idea](https://wiki.tox.im/GSoC/2015/Ideas#Modular_library_for_platform-dependent_audio.2C_video_and_desktop_capture) which overlaps with your project a little bit. Basically, we want to try to make a cross-platform library for audio, video and desktop capture for Tox GUIs (aka clients) to use, clients wouldn't have to implement their own audio, video and desktop capturing. It also goes beyond Tox, because if the library works well enough, other projects (SDL, for example, which has audio and video capturing somewhere on the roadmap), might use it and even contribute whatever they need for it to become usable for their project (or just fork, at the very least). It's not likely we will work on it anytime soon if we don't find a good college student to work on it as part of GSoC program though.

**Comment by frankpapenmeier** [comment]
issue should be closed because license was added some months ago

**Comment by nurupo** [comment]
Yep
